language: node_js

node_js:
  - "v17"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/topups

before_script:
  - psql -c 'create database  topups' -U postgres
  - psql -U postgres -d topups -a -f sql/db.sql

services:
  - postgresql